### ISSUE TITLE
AJAX handler 'mailSignup::onSignup' was not found.

### ISSUE THREAD

**Issue by Michael-Brooks** [rainlab/mailchimp-plugin#10] opened 2016-02-04 20:06 UTC
I have a clean install of October and installed the Mailchimp plugin. I have added the component from the components list and inserted the code. Tried to test with my own email and the alert above was shown.

**Comment by svetbg** [comment] 2016-02-22 14:07
I have exactly the same issue.

**Comment by svetbg** [comment] 2016-02-22 14:15
May be this helps:
https://github.com/rainlab/mailchimp-plugin/issues/2

**Comment by daftspunk** [comment] 2016-02-22 22:34
Duplicate of #2 

See http://octobercms.com/docs/cms/partials#life-cycle-limitations

**Closed as completed by daftspunk** 2016-02-22 22:34 UTC

**Comment by alinalamichhane** [comment] 2021-06-16 08:59
If you include the component in partial, you also have you include the same component in the layout in which you're including that partial. Worked for me. Hope it helps.
